# ==============================================================================
# HYPRLAND MAIN CONFIGURATION
# ==============================================================================

source = $HOME/.config/hypr/conf/tokens.conf
source = $HOME/.config/hypr/conf/monitors.conf
source = $HOME/.config/hypr/conf/plugins.conf
source = $HOME/.config/hypr/conf/theme.conf
source = $HOME/.config/hypr/conf/autostart.conf
source = $HOME/.config/hypr/conf/env.conf
source = $HOME/.config/hypr/conf/apps.conf
source = $HOME/.config/hypr/conf/layout.conf
source = $HOME/.config/hypr/conf/input.conf
source = $HOME/.config/hypr/conf/binds.conf
source = $HOME/.config/hypr/conf/plugin-hyprspace.conf
source = $HOME/.config/hypr/conf/plugin-canvas.conf
source = $HOME/.config/hypr/conf/screenshots.conf
source = $HOME/.config/hypr/conf/xwayland.conf
