# ==============================================================================
# APPS
# ==============================================================================
$terminal    = foot
$fileManager = nemo
$menu        = $HOME/.config/rofi/scripts/rofi-push.sh
$powermenu   = $HOME/.config/rofi/scripts/rofi-push.sh
