# --- Autostart ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

exec-once = sh -lc '$HOME/.local/bin/waybar-toggle restart'

exec-once = systemctl --user restart hypridle.service
