# --- Autostart ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

exec-once = systemctl --user restart waybar.service

exec-once = systemctl --user restart hypridle.service
