# ==============================================================================
# AUTOSTART
# ==============================================================================
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY

exec-once = sh -lc 'pkill waybar; (waybar </dev/null >/dev/null 2>&1 & disown)'

exec-once = systemctl --user restart hypridle.service
