# ==============================================================================
# INPUT
# ==============================================================================
input {
  kb_layout = fr
  kb_options = ctrl:nocaps
  follow_mouse = 1
  natural_scroll = yes

  touchpad {
    natural_scroll = yes
  }
}

cursor {
  enable_hyprcursor = true
  no_hardware_cursors = false
}
