# --- Hyprspace ---
bind = $mod, D, exec, $HOME/.local/bin/hypr-overview-toggle

plugin {
  overview {
    panelColor = rgba(1e1e2eef)
    workspaceActiveBackground = rgba(0d141b61)
    workspaceInactiveBackground = rgba(0d141b47)
    workspaceActiveBorder = $accent
    workspaceInactiveBorder = rgba(b7bcc638)
    workspaceBorderSize = 2
    drawActiveWorkspace = true
    showNewWorkspace = false
    overrideGaps = false
    workspaceActiveColor = $accent
    autoScroll = true
    exitOnClick = true
    switchOnDrop = true
    exitOnSwitch = true
    autoDrag = true
  }
}
