# ------------------------------------------------------------------------------
# PLUGIN LOAD
# ------------------------------------------------------------------------------
plugin = $HOME/.local/lib/libhypr-darkwindow.so
plugin = $HOME/.local/lib/hypr-canvas.so
# plugin = $HOME/.local/lib/hyprexpo.so
plugin = $HOME/.local/lib/hyprspace.so

