# Screenshots
bind = , Print, exec, sh -lc 'mkdir -p "$HOME/Images" && grim "$HOME/Images/Screenshot-$(date +%Y-%m-%d_%H-%M-%S).png" && notify-send "Screenshot saved"'
bind = $mod, Print, exec, sh -lc 'mkdir -p "$HOME/Images" && grim -g "$(slurp)" "$HOME/Images/Screenshot-$(date +%Y-%m-%d_%H-%M-%S).png" && notify-send "Screenshot saved"'
bind = $mod SHIFT, S, exec, sh -lc 'mkdir -p "$HOME/Images" && grim -g "$(slurp)" "$HOME/Images/Screenshot-$(date +%Y-%m-%d_%H-%M-%S).png" && notify-send "Screenshot saved"'
